controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\data\Pagination;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\data\ActiveDataProvider;
use yii\filters\VerbFilter;

use app\models\LoginForm;
use app\models\ContactForm;

use app\models\User;
use app\models\Group;
use app\models\Day;
use app\models\Lesson;

class SiteController extends Controller {

	public function init()
	{
		parent::init();
		if (Yii::$app->user->isGuest) {
			return $this->redirect('/auth/login');
		}
	}

	public function behaviors() {
		return [
		];
	}

	public function actions() {
		return [
			'error' => [
				'class' => 'yii\web\ErrorAction',
			],
			'captcha' => [
				'class' => 'yii\captcha\CaptchaAction',
				'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
			],
		];
	}

	public function actionIndex() {
		if (Yii::$app->user->isGuest) {
			return $this->redirect('/auth/login');
		} else {
			return $this->redirect('/site/main');
		}
	}

	public function actionMain() {

		$dataProvider = new ActiveDataProvider([ 'query' => Group::find() ]);

		return $this->render('index', [
			'dataProvider' => $dataProvider,
		]);
	}

	public function actionAddGroup()
	{
		$model = new Group();

		if ($model->load(Yii::$app->request->post())) {
			// $model->title = Yii::$app->request->post()['Group']['title'];
			$model->save();
			return $this->redirect(['index']);
		} else {
			return $this->render('add-group', [
				'model' => $model,
			]);
		}
	}

	public function actionUpdateGroup($id)
	{
		$model = Group::findOne($id);

		if ($model->load(Yii::$app->request->post())) {
			$model->save();
			return $this->redirect(['index']);
		} else {
			return $this->render('update-group', [
				'model' => $model,
			]);
		}
	}

	public function actionDeleteGroup($id)
	{
		Group::findOne($id)->delete();

		return $this->redirect(['index']);
	}

	public function actionAddLesson($group, $day)
	{
		$model = new Lesson();

		if ($model->load(Yii::$app->request->post())) {
			$model->group_id = $group;
			$model->day_id = $day;
			$model->save();
			return $this->redirect(['day', 'group' => $group, 'id' => $day]);
		} else {
			return $this->render('add-lesson', [
				'model' => $model,
			]);
		}
	}

	public function actionUpdateLesson($id)
	{
		$model = Lesson::findOne($id);

		if ($model->load(Yii::$app->request->post())) {
			$model->save();
			return $this->redirect(['group', 'id' => $model->group_id]);
		} else {
			return $this->render('update-lesson', [
				'model' => $model,
			]);
		}
	}

	public function actionDeleteLesson($id)
	{
		Lesson::findOne($id)->delete();

		return $this->redirect(['index']);
	}

	public function actionGroup($id)
	{
		return $this->render('group', [
			'dataProvider' => $this->getDays(),
		]);
	}

	public function actionDay($group, $id)
	{
		$dataProvider = new ActiveDataProvider([ 'query' => Lesson::find()->where(['group_id'=>$group, 'day_id'=>$id]) ]);
		return $this->render('lessons', [
			'day' => Day::findOne($id)->title,
			'dataProvider' => $dataProvider,
		]);
	}

	private function getDaysArray(){
		$days = [];
		$all_days = Day::find()->all();

		for ($i=0; $i < count($all_days); $i++) {
			$item = $all_days[$i];
			$days[$item->id] = $item->title;
		}
		return $days;
	}

	private function getDays(){
		return new ActiveDataProvider([ 'query' => Day::find() ]);
	}

}

views/partials/footer.php
<footer class="footer">
	<div class="footer__block block no-margin-bottom">
		<div class="container-fluid text-center">
			<!-- Please do not remove the backlink to us unless you support us at https://bootstrapious.com/donate. It is part of the license conditions. Thank you for understanding :)-->
			<p class="no-margin-bottom">2017 &copy;.</p>
		</div>
	</div>
</footer>

views/partials/header.php
<?php 
use app\models\User;
?>
<header class="header">
   <nav class="navbar navbar-expand-lg">
      <div class="container-fluid d-flex align-items-center justify-content-between">
         <div class="navbar-header">
            <a href="index.html" class="navbar-brand">
               <?php if(User::isAdmin()): ?>
                  <div class="brand-text brand-big visible text-uppercase"><strong class="text-primary">Админ</strong><strong> панель</strong></div>
                  <div class="brand-text brand-sm"><strong class="text-primary">А</strong><strong>П</strong></div>
               <?php else: ?>
                  <div class="brand-text brand-big visible text-uppercase"><strong class="text-primary">Панель</strong><strong>студента</strong></div>
                  <div class="brand-text brand-sm"><strong class="text-primary">П</strong><strong>С</strong></div>
               <?php endif ?>
            </a>
            <button class="sidebar-toggle"><i class="fa fa-long-arrow-left"></i></button>
         </div>
         <ul class="right-menu list-inline no-margin-bottom">
            <li class="list-inline-item logout"><a id="logout" href="/auth/logout" class="nav-link">Выход есть всегда <i class="icon-logout"></i></a></li>
         </ul>
      </div>
   </nav>
</header>

views/partials/item.php
<?php
use yii\helpers\Url;
?>
<?php foreach($projects as $project):?>
	<article class="post_type_4">
		<div class="feature">
			<div class="image">
				<a href="<?= Url::toRoute(['site/view', 'id'=>$project->id]);?>">
					<img class="item-img" src="<?= $project->getImage();?>" alt=""><span class="hover"></span>
				</a>
			</div>
		</div>
		
		<div class="content">
			<div class="info">
				<div class="date"><?= $project->getDate();?></div>
				<div class="stats">
					<div class="views"><?= (int)$project->viewed ?></div>
				</div>
			</div>
			
			<div class="title">
				<a href="<?= Url::toRoute(['site/view', 'id'=>$project->id]);?>"><?= $project->title ?></a>
			</div>
			
			<div class="line_1"></div>
		</div>
	</article>
<?php endforeach; ?>

views/partials/sidebar.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use app\models\Group;
use app\models\User;

$groups = [];
$all_groups = Group::find()->all();

for ($i=0; $i < count($all_groups); $i++) {
	$item = $all_groups[$i];
	$groups[] = [
		'label' => $item->title,
		'url' => "/site/group?id=$item->id",
		'active' => ($this->context->route == 'site/group' and $_GET['id'] == $item->id)
	];
}

?>

<nav id="sidebar">
	<span class="heading">Панель</span>
	<ul class="list-unstyled">
		<li><a href="/"><i class="icon-home"></i>Главная</a></li>
		<li><a href="#dashvariants" aria-expanded="false" data-toggle="collapse"> <i class="icon-windows"></i>Группы</a>
			<ul id="dashvariants" class="collapse list-unstyled">
				<?php foreach($groups as $item): ?>
					<li class=" <?= (($item['active'] == 1) ? 'active' : '') ?>"><a href="<?= $item['url'] ?>"><?= $item['label'] ?></a></li>
				<?php endforeach ?>
				<?php if (User::isAdmin()): ?>
				<li class="<?= ($this->context->route == 'site/add-group') ? 'active' : '' ?>"><a href="/site/add-group"><i class="fa fa-plus"></i> Добавить группу</a></li>
				<?php endif ?>
			</ul>
		</li>
	</ul>
</nav>