controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\data\Pagination;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\data\ActiveDataProvider;
use yii\filters\VerbFilter;

use app\models\LoginForm;
use app\models\ContactForm;

use app\models\User;
use app\models\Group;
use app\models\Day;
use app\models\Lesson;

class SiteController extends Controller {

	public function init()
	{
		parent::init();
		if (Yii::$app->user->isGuest) {
			return $this->redirect('/auth/login');
		}
	}

	public function behaviors() {
		return [
		];
	}

	public function actions() {
		return [
			'error' => [
				'class' => 'yii\web\ErrorAction',
			],
			'captcha' => [
				'class' => 'yii\captcha\CaptchaAction',
				'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
			],
		];
	}

	public function actionIndex() {
		if (Yii::$app->user->isGuest) {
			return $this->redirect('/auth/login');
		} else {
			return $this->redirect('/site/main');
		}
	}

	public function actionMain() {

		$dataProvider = new ActiveDataProvider([ 'query' => Group::find() ]);

		return $this->render('index', [
			'dataProvider' => $dataProvider,
		]);
	}

	public function actionAddGroup()
	{
		$model = new Group();

		if ($model->load(Yii::$app->request->post())) {
			// $model->title = Yii::$app->request->post()['Group']['title'];
			$model->save();
			return $this->redirect(['index']);
		} else {
			return $this->render('add-group', [
				'model' => $model,
			]);
		}
	}

	public function actionUpdateGroup($id)
	{
		$model = Group::findOne($id);

		if ($model->load(Yii::$app->request->post())) {
			$model->save();
			return $this->redirect(['index']);
		} else {
			return $this->render('update-group', [
				'model' => $model,
			]);
		}
	}

	public function actionDeleteGroup($id)
	{
		Group::findOne($id)->delete();

		return $this->redirect(['index']);
	}

	public function actionAddLesson($group, $day)
	{
		$model = new Lesson();

		if ($model->load(Yii::$app->request->post())) {
			$model->group_id = $group;
			$model->day_id = $day;
			$model->save();
			return $this->redirect(['day', 'group' => $group, 'id' => $day]);
		} else {
			return $this->render('add-lesson', [
				'model' => $model,
			]);
		}
	}

	public function actionUpdateLesson($id)
	{
		$model = Lesson::findOne($id);

		if ($model->load(Yii::$app->request->post())) {
			$model->save();
			return $this->redirect(['group', 'id' => $model->group_id]);
		} else {
			return $this->render('update-lesson', [
				'model' => $model,
			]);
		}
	}

	public function actionDeleteLesson($id)
	{
		Lesson::findOne($id)->delete();

		return $this->redirect(['index']);
	}

	public function actionGroup($id)
	{
		return $this->render('group', [
			'dataProvider' => $this->getDays(),
		]);
	}

	public function actionDay($group, $id)
	{
		$dataProvider = new ActiveDataProvider([ 'query' => Lesson::find()->where(['group_id'=>$group, 'day_id'=>$id]) ]);
		return $this->render('lessons', [
			'day' => Day::findOne($id)->title,
			'dataProvider' => $dataProvider,
		]);
	}

	private function getDaysArray(){
		$days = [];
		$all_days = Day::find()->all();

		for ($i=0; $i < count($all_days); $i++) {
			$item = $all_days[$i];
			$days[$item->id] = $item->title;
		}
		return $days;
	}

	private function getDays(){
		return new ActiveDataProvider([ 'query' => Day::find() ]);
	}

}

views/site/add-group.php
<?php 

use yii\helpers\Html;
use yii\widgets\ActiveForm;

$this->title = Yii::t('app', 'Новая группа');
?>

<br>
<br>
<section class="no-padding-top">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <div class="block">
          <div class="title"><strong class="d-block">Добавить группу</strong></div>
          <div class="block-body">
            <?php $form = ActiveForm::begin(); ?>

            <?= $form->field($model, 'title')->textInput() ?>

            <div class="form-group center">
              <?= Html::submitButton('Добавить', ['class' => 'btn btn-success']) ?>
            </div>
            <?php ActiveForm::end(); ?>

          </div>
        </div>
      </div>
    </div>
  </div>
</section>

views/site/add-lesson.php
<?php 

use yii\helpers\Html;
use yii\widgets\ActiveForm;

$this->title = Yii::t('app', 'Новая пара');
?>

<br>
<br>
<section class="no-padding-top">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <div class="block">
          <div class="title"><strong class="d-block">Добавить пару</strong></div>
          <div class="block-body">
            <?php $form = ActiveForm::begin(); ?>

            <?= $form->field($model, 'title')->textInput() ?>
            <?= $form->field($model, 'time')->textInput() ?>

            <div class="form-group center">
              <?= Html::submitButton('Добавить', ['class' => 'btn btn-success']) ?>
            </div>
            <?php ActiveForm::end(); ?>

          </div>
        </div>
      </div>
    </div>
  </div>
</section>

views/site/group.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

$this->title = 'Выберите день';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="page-header no-margin-bottom">
  <div class="container-fluid">
    <h2 class="h5 no-margin-bottom"><?= Html::encode($this->title) ?></h2>
  </div>
</div>

<ul class="breadcrumb">
  <div class="container-fluid">
  </div>
</ul>

<section class="no-padding-top">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <div class="block margin-bottom-sm">
          <div class="title"><strong><?= Html::encode($this->title) ?></strong></div>
          <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'columns' => [
              'title',
              [
                'label'=>'Действия', 
                'headerOptions' => ['width' => '100'],
                'format' => 'raw',
                'value' => function($data){
                  return Html::a('Перейти', ['site/day', 'group'=>$_GET['id'], 'id'=>$data->id ]);
                },
              ],
            ],
            ]); ?>
          </div>
        </div>
      </div>
    </div>
  </section>

views/site/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use app\models\User;

$this->title = 'Группы';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="page-header no-margin-bottom">
  <div class="container-fluid">
    <h2 class="h5 no-margin-bottom"><?= Html::encode($this->title) ?></h2>
  </div>
</div>

<ul class="breadcrumb">
  <div class="container-fluid">
  </div>
</ul>

<section class="no-padding-top">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <div class="block margin-bottom-sm">
          <div class="title"><strong><?= Html::encode($this->title) ?></strong></div>
          <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'columns' => [
              'id',
              'title',
              [
                'class' => 'yii\grid\ActionColumn',
                'header'=>'Действия',
                'visible' => (int)(User::isAdmin()),
                'headerOptions' => ['width' => '80'],
                'template' => '{update} {delete}',
                'buttons' => [
                  'update' => function ($url, $model) {
                    return Html::a('<span class="fa fa-pencil"></span>', ['site/update-group', 'id'=>$model->id ], [
                      'title' => Yii::t('app', 'lead-update'),
                    ]);
                  },
                  'delete' => function ($url, $model) {
                    return Html::a('<span class="fa fa-trash"></span>', ['site/delete-group', 'id'=>$model->id ], [
                      'title' => Yii::t('app', 'lead-delete'),
                    ]);
                  }
                ],
              ],
            ],
            ]); ?>
          </div>
        </div>
      </div>
    </div>
  </section>

views/site/lessons.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use app\models\User;

$this->title = 'Пары на ' . $day;
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="page-header no-margin-bottom">
  <div class="container-fluid">
    <h2 class="h5 no-margin-bottom"><?= Html::encode($this->title) ?></h2>
  </div>
</div>

<ul class="breadcrumb">
  <div class="container-fluid">
  </div>
</ul>

<section class="no-padding-top">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <div class="block margin-bottom-sm">
        <?php if(User::isAdmin()): ?>
          <?= Html::a('Добавить пару', ['site/add-lesson', 'group'=> $_GET['group'], 'day'=> $_GET['id'] ]);  ?>
        <?php endif ?>
          <div class="title"><strong><?= Html::encode($this->title) ?></strong></div>
          <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'columns' => [
              'time',
              'title',
              [
                'class' => 'yii\grid\ActionColumn',
                'header'=>'Действия', 
                'visible' => (int)(User::isAdmin()),
                'headerOptions' => ['width' => '80'],
                'template' => '{update} {delete}',
                'buttons' => [
                  'update' => function ($url, $model) {
                    return Html::a('<span class="fa fa-pencil"></span>', ['site/update-lesson', 'id'=>$model->id ], [
                      'title' => Yii::t('app', 'lead-update'),
                    ]);
                  },
                  'delete' => function ($url, $model) {
                    return Html::a('<span class="fa fa-trash"></span>', ['site/delete-lesson', 'id'=>$model->id ], [
                      'title' => Yii::t('app', 'lead-delete'),
                    ]);
                  }
                ],
              ],
            ],
            ]); ?>
          </div>
        </div>
      </div>
    </div>
  </section>

views/site/update-group.php
<?php 

use yii\helpers\Html;
use yii\widgets\ActiveForm;

$this->title = Yii::t('app', 'Новая группа');
?>

<br>
<br>
<section class="no-padding-top">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <div class="block">
          <div class="title"><strong class="d-block">Обновить группу</strong></div>
          <div class="block-body">
            <?php $form = ActiveForm::begin(); ?>

            <?= $form->field($model, 'title')->textInput() ?>

            <div class="form-group center">
              <?= Html::submitButton('Обновить', ['class' => 'btn btn-success']) ?>
            </div>
            <?php ActiveForm::end(); ?>

          </div>
        </div>
      </div>
    </div>
  </div>
</section>

views/site/update-lesson.php
<?php 

use yii\helpers\Html;
use yii\widgets\ActiveForm;

$this->title = Yii::t('app', 'Новая пара');
?>

<br>
<br>
<section class="no-padding-top">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <div class="block">
          <div class="title"><strong class="d-block">Обновить пару</strong></div>
          <div class="block-body">
            <?php $form = ActiveForm::begin(); ?>

            <?= $form->field($model, 'title')->textInput() ?>
            <?= $form->field($model, 'time')->textInput() ?>

            <div class="form-group center">
              <?= Html::submitButton('Обновить', ['class' => 'btn btn-success']) ?>
            </div>
            <?php ActiveForm::end(); ?>

          </div>
        </div>
      </div>
    </div>
  </div>
</section>